### ISSUE TITLE
Request, more than an "issue"

### ISSUE THREAD

**Issue by paradisewoods** [Kiingy/MuteWoWSounds#2]
I'm sorry to bother you, but even after following your directions, I was unable to find the soundfile for the summoning sound that The Dreadwake uses - the horn and the bells and all. I couldn't find any related sound files on WoWhead, or in the sound file directory located at wow.tools/files
I've asked a few others for help, and either get redirected here, or to the above address. I haven't had any lucky trying to find it in either place.
Is there any chance you can help me find it? Is it hidden or otherwise unable to be muted? Any tips or advice would be appreciated!
Thanks

**Comment by Kiingy** [comment]
There's no easy way to find the sounds if Blizzard hasnt named them appropriately, you'll have to just go down the list and listen to them all until you found it,

Good luck!
https://www.wowhead.com/sounds
