### ISSUE TITLE
Distributed TOC has entry for optional CustomSounds.lua

### ISSUE THREAD

**Issue by Clattuc** [Kiingy/MuteWoWSounds#3]
The MuteAnnoyingWoWSounds.toc distributed with the current release says
```
## Interface: 90001
## Title: MuteAnnoyingWoWSounds
## Description: Mutes WoWs annoying sounds.
## Author: Kiingy AU/US-Frostmourne

SoundMutes.lua
CustomSounds.lua
```
but the Custom file isn't included and won't exist unless the player hand codes it or downloads your special tool.

I suggest that you either comment out the Custom line with an explanatory comment, like

```
## Uncomment this if you have created a Custom Sounds file
## CustomSounds.lua
```

or else provide a "dummy" CustomSounds.lua file with the distribution, to be edited or overwritten with the player's own if they choose.

Thank you for a good addon - I used the tool to add my annoying warlock Felsteed to the list!

```
# MY SOUNDS
felsteed mount - 3183
```

**Comment by Clattuc** [comment]
I realized after the fact that I opened this in the tool github, not the addon, sorry

**Comment by Kiingy** [comment]
Thanks for the report, was a mistake it was left in. It's been fixed.
